---
abstract: 'A Perl extension, allow method call with bare blocks afterward.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.92
  Test::Perl::Critic: 1.01
  Test::Pod: 1.40
  Test::Spelling: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlX-MethodCallWithBlock
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  B::Generate: 1.20
  B::Hooks::EndOfScope: 0.08
  B::Hooks::Parser: 0.09
  B::OPCheck: 0.28
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/gugod/PerlX-MethodCallWithBlock.git
version: 0.01
